### ISSUE TITLE
关于local_search没有结果的问题

### ISSUE THREAD

**Issue by formattedzzz** [codefine/hexo-theme-mellow#1]
**站点配置**：
```
search:
  path: search.xml
  field: post
  format: html
  limit: 1000
```
**主题配置**：

```
#搜索
local_search: true
```
之后并没有在根目录下看到search.xml的文件，请问博主怎么解决，有没有其他要注意的？
