### ISSUE TITLE
代码背景变色，可以变成黑色吗

### ISSUE THREAD

**Issue by YuanLiChenAi** [codefine/hexo-theme-mellow#19]
![tim 20180319200857](https://user-images.githubusercontent.com/37205011/37594895-a40598ec-2bb1-11e8-8102-d44c28d99b68.jpg)
![tim 20180319201156](https://user-images.githubusercontent.com/37205011/37594936-c98f17b4-2bb1-11e8-82c2-53229d45fb4f.jpg)

**Comment by codefine** [comment]
@YuanLiChenAi 没问题的。
找到文件`mellow/source/css/_partial/highlight.less`，修改区域为前几行代码：
``` css
@h-background: #f5f5f5; // 背景色
@h-current-line: #efefef;
@h-selectioon: #d6d6d6;
@h-foreground: #4d4d4c;
@h-comment: #8e908c; // 注释颜色
@h-red: #c82829;
@h-orange: #f5871f; // 高亮色
@h-yellow: #eab700;
@h-green: #718c00;
@h-aqua: #3e999f;
@h-blue: #4271ae;
@h-purple: #8959a8;
@h-fs: @font-size;

.codeBlock() {
    position: relative;
    overflow-x: auto;
    padding: 20px;
    font-size: @h-fs;
    line-height: @h-fs*1.6;
    background: @h-background;
}

.line-numbers() {
    color: @primaryColor_2; // 行号色
    font-size: 0.85em;
}
```
