### ISSUE TITLE
左侧栏跳转到其他网页，失败

### ISSUE THREAD

**Issue by LiuFG** [codefine/hexo-theme-mellow#56]
问题描述：从bloghome跳转到HOMEPAGE成功，但是从categories跳转到HOMEPAGE失败，跳转网页为`http://fenggangliu.top/http:/en.fenggangliu.top/`，应该为`https://en.fenggangliu.top/`。
我的个人博客地址为[LiuFG](http://fenggangliu.top)，可复现。
以下是_config.yml中左侧栏部分列表的设置：
```
menu:
  HOMEPAGE:
    url: http://en.fenggangliu.top/
    target: _blank
    icon: id-card
  bloghome:
    text: BLOG
    url: /
    icon: home
  categories:
    text: CATEGORIES
    url: /categories
    icon: th-list
```
请问在哪里可以修改？十分感谢
