### ISSUE TITLE
Cannot GET /

### ISSUE THREAD

**Issue by lucasjinreal** [codefine/hexo-theme-mellow#6]
clone了主题，在项目根目录的_config.yml 配置了主题，然后hexo g hexo s，
然后说找不到主页：
```
Cannot GET /
```
啥情况啊这是

**Comment by formattedzzz** [comment]
贴上报错的代码

**Comment by lucasjinreal** [comment]
多谢回答，没有任何报错信息，hexo g也可以生成，hexo s 就无法访问到主页，一面空白显示无法get , 我估计可能是路径哪里写错了，我主题文件没有任何修改，这是我的全局config设置：

```
# Site
title: Lewis Jin
subtitle: AI enthusiasts
description: A man awesome like a God
author: Lewis Jin
language:
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://jinfagang.gitlab.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 20
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
plugins:
   hexo-renderer-mathjax
   hexo-generator-search 
   hexo-generator-topindex 
   hexo-helper-qrcode 
   hexo-renderer-less

#theme: hexo-theme-ochuunn
# theme: solar-theme-hexo
theme: hexo-theme-mellow
```
不知道大佬可发现这个配置有什么问题，求指点迷津啊！！
